### ISSUE TITLE
Pickup time is unintentionally automatically set.

### ISSUE THREAD

**Issue by aubrel** [meitar/flora-posidonia#33]
Is it reproducible: Yes

### Steps to Produce/Reproduce

1. Buy a product so as to create a new order.
1. As an admin or shop manager, edit that order.
1. Note that pickup time has current date and time, but both should be empty.

### Expected Results
Pickup time remains empty until explicitly set by admin or shop manager.

### Actual Results
Pickup time is filled in, if it is empty, when loading the order page. This leads to unintentionally setting a pickup time when order is saved.

### Workarounds
Manually re-set or erase pickup time after it has been unintentionally automatically set.

**Comment by meitar** [comment]
@aubrel Please download the head of the `issue-33` branch and let me know if this fixes (and does not break) any existing pickup time functionality. If so, we'll merge to master and deploy a new patch release.
