### ISSUE TITLE
Create static content pages

### ISSUE THREAD

**Issue by meitar** [meitar/flora-posidonia#5]
We'll need pages like "About," maybe a generic "Contact" page, or anything else you want.

* [x] [Home page](https://github.com/meitar/flora-posidonia/wiki/Home_page)
* [x] [About page](https://github.com/meitar/flora-posidonia/wiki/About_page)
* [x] [Contact page](https://github.com/meitar/flora-posidonia/wiki/Contact_page)

**Comment by aubrel** [comment]
Created static "About" and "Contact" pages. "Contact" page incorporates a test of Form 7.

**Comment by meitar** [comment]
> Created static "About" and "Contact" pages. "Contact" page incorporates a test of Form 7.

@aubrel Awesome! Where did you put the content for these pages? I don't see it on the wiki or the live site.

**Comment by aubrel** [comment]
I put it on the test site, just because I was messing with some other stuff and am (still) paranoid about breaking things. o-o  I will move it over to the live site shortly, though!

**Comment by meitar** [comment]
Ah, okay! If you want to "commit" this into an automatable process, be sure to add the content itself to the wiki so that that it ends up in our runbooks and/or code. Otherwise, yay, you made it work and we don't necessarily have to track this content "like code" if you don't want to. (It's up to you how much of a stickler you'd like me to be about this in terms of making sure static content pages get added on new builds by default.)

**Comment by meitar** [comment]
It also occurs to me that you probably want home page content, too. Reopening.

**Comment by aubrel** [comment]
Added home page content as well as an FAQ page to the wiki.
